---
layout: nil
---

application: itsabodybuildingblog
version: 3
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /atom.xml
  static_files: atom.xml
  upload: atom.xml

- url: /css
  static_dir: css

- url: /i
  static_dir: i

- url: /js
  static_dir: js

{% for post in site.posts %}
- url: {{ post.id }}/?
  static_files: {{ post.id | remove_first:"/" }}/index.html
  upload: {{ post.id | remove_first:"/" }}/index.html
{% endfor %}

- url: /
  static_files: index.html
  upload: index.html

- url: .*
  script: main.py

